services:
  postgres-product:
    image: postgres:15-alpine
    container_name: postgres-product
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product-db
    volumes:
      - postgres-product-data:/var/lib/postgresql/data
    networks:
      - microservices-net

  postgres-order:
    image: postgres:15-alpine
    container_name: postgres-order
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=order-db
    volumes:
      - postgres-order-data:/var/lib/postgresql/data
    networks:
      - microservices-net

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak-realm-export.json:/opt/keycloak/data/import/realm.json
    networks:
      - microservices-net

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-product:5432/product-db
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8080/realms/sdia-realm
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/sdia-realm/protocol/openid-connect/certs
    depends_on:
      - postgres-product
      - keycloak
    networks:
      - microservices-net

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-order:5432/order-db
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8080/realms/sdia-realm
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/sdia-realm/protocol/openid-connect/certs
      - PRODUCT_SERVICE_URL=http://product-service:8081
    depends_on:
      - postgres-order
      - keycloak
      - product-service
    networks:
      - microservices-net

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8085:8085"
    environment:
      - SPRING_CLOUD_GATEWAY_ROUTES_0_ID=product-service
      - SPRING_CLOUD_GATEWAY_ROUTES_0_URI=http://product-service:8081
      - SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0=Path=/products/**
      - SPRING_CLOUD_GATEWAY_ROUTES_1_ID=order-service
      - SPRING_CLOUD_GATEWAY_ROUTES_1_URI=http://order-service:8082
      - SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0=Path=/orders/**
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:8080/realms/sdia-realm
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/sdia-realm/protocol/openid-connect/certs
    depends_on:
      - product-service
      - order-service
    networks:
      - microservices-net

  react-app:
    build: ./react-app
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - gateway
    networks:
      - microservices-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres-product
      - postgres-order
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres-product-data:
  postgres-order-data: